// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageHeartBeat.proto

#ifndef PROTOBUF_MessageHeartBeat_2eproto__INCLUDED
#define PROTOBUF_MessageHeartBeat_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageHeartBeat_2eproto();
void protobuf_AssignDesc_MessageHeartBeat_2eproto();
void protobuf_ShutdownFile_MessageHeartBeat_2eproto();

class MessageHeartBeat;

// ===================================================================

class MessageHeartBeat : public ::google::protobuf::Message {
 public:
  MessageHeartBeat();
  virtual ~MessageHeartBeat();

  MessageHeartBeat(const MessageHeartBeat& from);

  inline MessageHeartBeat& operator=(const MessageHeartBeat& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageHeartBeat& default_instance();

  void Swap(MessageHeartBeat* other);

  // implements Message ----------------------------------------------

  MessageHeartBeat* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageHeartBeat& from);
  void MergeFrom(const MessageHeartBeat& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MessageHeartBeat)
 private:
  inline void set_has_code();
  inline void clear_has_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 code_;
  friend void  protobuf_AddDesc_MessageHeartBeat_2eproto();
  friend void protobuf_AssignDesc_MessageHeartBeat_2eproto();
  friend void protobuf_ShutdownFile_MessageHeartBeat_2eproto();

  void InitAsDefaultInstance();
  static MessageHeartBeat* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageHeartBeat

// required int32 code = 1;
inline bool MessageHeartBeat::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageHeartBeat::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageHeartBeat::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageHeartBeat::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 MessageHeartBeat::code() const {
  // @@protoc_insertion_point(field_get:MessageHeartBeat.code)
  return code_;
}
inline void MessageHeartBeat::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:MessageHeartBeat.code)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageHeartBeat_2eproto__INCLUDED
