// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageTaskDeliverReply.proto

#ifndef PROTOBUF_MessageTaskDeliverReply_2eproto__INCLUDED
#define PROTOBUF_MessageTaskDeliverReply_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageTaskDeliverReply_2eproto();
void protobuf_AssignDesc_MessageTaskDeliverReply_2eproto();
void protobuf_ShutdownFile_MessageTaskDeliverReply_2eproto();

class MessageTaskDeliverReply;

// ===================================================================

class MessageTaskDeliverReply : public ::google::protobuf::Message {
 public:
  MessageTaskDeliverReply();
  virtual ~MessageTaskDeliverReply();

  MessageTaskDeliverReply(const MessageTaskDeliverReply& from);

  inline MessageTaskDeliverReply& operator=(const MessageTaskDeliverReply& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageTaskDeliverReply& default_instance();

  void Swap(MessageTaskDeliverReply* other);

  // implements Message ----------------------------------------------

  MessageTaskDeliverReply* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageTaskDeliverReply& from);
  void MergeFrom(const MessageTaskDeliverReply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string taskid = 1;
  inline bool has_taskid() const;
  inline void clear_taskid();
  static const int kTaskidFieldNumber = 1;
  inline const ::std::string& taskid() const;
  inline void set_taskid(const ::std::string& value);
  inline void set_taskid(const char* value);
  inline void set_taskid(const char* value, size_t size);
  inline ::std::string* mutable_taskid();
  inline ::std::string* release_taskid();
  inline void set_allocated_taskid(::std::string* taskid);

  // required int32 code = 2;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 2;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // required string message = 3;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 3;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:MessageTaskDeliverReply)
 private:
  inline void set_has_taskid();
  inline void clear_has_taskid();
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_message();
  inline void clear_has_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* taskid_;
  ::std::string* message_;
  ::google::protobuf::int32 code_;
  friend void  protobuf_AddDesc_MessageTaskDeliverReply_2eproto();
  friend void protobuf_AssignDesc_MessageTaskDeliverReply_2eproto();
  friend void protobuf_ShutdownFile_MessageTaskDeliverReply_2eproto();

  void InitAsDefaultInstance();
  static MessageTaskDeliverReply* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageTaskDeliverReply

// required string taskid = 1;
inline bool MessageTaskDeliverReply::has_taskid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageTaskDeliverReply::set_has_taskid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageTaskDeliverReply::clear_has_taskid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageTaskDeliverReply::clear_taskid() {
  if (taskid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    taskid_->clear();
  }
  clear_has_taskid();
}
inline const ::std::string& MessageTaskDeliverReply::taskid() const {
  // @@protoc_insertion_point(field_get:MessageTaskDeliverReply.taskid)
  return *taskid_;
}
inline void MessageTaskDeliverReply::set_taskid(const ::std::string& value) {
  set_has_taskid();
  if (taskid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    taskid_ = new ::std::string;
  }
  taskid_->assign(value);
  // @@protoc_insertion_point(field_set:MessageTaskDeliverReply.taskid)
}
inline void MessageTaskDeliverReply::set_taskid(const char* value) {
  set_has_taskid();
  if (taskid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    taskid_ = new ::std::string;
  }
  taskid_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageTaskDeliverReply.taskid)
}
inline void MessageTaskDeliverReply::set_taskid(const char* value, size_t size) {
  set_has_taskid();
  if (taskid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    taskid_ = new ::std::string;
  }
  taskid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageTaskDeliverReply.taskid)
}
inline ::std::string* MessageTaskDeliverReply::mutable_taskid() {
  set_has_taskid();
  if (taskid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    taskid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageTaskDeliverReply.taskid)
  return taskid_;
}
inline ::std::string* MessageTaskDeliverReply::release_taskid() {
  clear_has_taskid();
  if (taskid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = taskid_;
    taskid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageTaskDeliverReply::set_allocated_taskid(::std::string* taskid) {
  if (taskid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete taskid_;
  }
  if (taskid) {
    set_has_taskid();
    taskid_ = taskid;
  } else {
    clear_has_taskid();
    taskid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageTaskDeliverReply.taskid)
}

// required int32 code = 2;
inline bool MessageTaskDeliverReply::has_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageTaskDeliverReply::set_has_code() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageTaskDeliverReply::clear_has_code() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageTaskDeliverReply::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 MessageTaskDeliverReply::code() const {
  // @@protoc_insertion_point(field_get:MessageTaskDeliverReply.code)
  return code_;
}
inline void MessageTaskDeliverReply::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:MessageTaskDeliverReply.code)
}

// required string message = 3;
inline bool MessageTaskDeliverReply::has_message() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageTaskDeliverReply::set_has_message() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageTaskDeliverReply::clear_has_message() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageTaskDeliverReply::clear_message() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& MessageTaskDeliverReply::message() const {
  // @@protoc_insertion_point(field_get:MessageTaskDeliverReply.message)
  return *message_;
}
inline void MessageTaskDeliverReply::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set:MessageTaskDeliverReply.message)
}
inline void MessageTaskDeliverReply::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageTaskDeliverReply.message)
}
inline void MessageTaskDeliverReply::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageTaskDeliverReply.message)
}
inline ::std::string* MessageTaskDeliverReply::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageTaskDeliverReply.message)
  return message_;
}
inline ::std::string* MessageTaskDeliverReply::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageTaskDeliverReply::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageTaskDeliverReply.message)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageTaskDeliverReply_2eproto__INCLUDED
