// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageTaskLogsQuery.proto

#ifndef PROTOBUF_MessageTaskLogsQuery_2eproto__INCLUDED
#define PROTOBUF_MessageTaskLogsQuery_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageTaskLogsQuery_2eproto();
void protobuf_AssignDesc_MessageTaskLogsQuery_2eproto();
void protobuf_ShutdownFile_MessageTaskLogsQuery_2eproto();

class MessageTaskLogsQuery;

// ===================================================================

class MessageTaskLogsQuery : public ::google::protobuf::Message {
 public:
  MessageTaskLogsQuery();
  virtual ~MessageTaskLogsQuery();

  MessageTaskLogsQuery(const MessageTaskLogsQuery& from);

  inline MessageTaskLogsQuery& operator=(const MessageTaskLogsQuery& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageTaskLogsQuery& default_instance();

  void Swap(MessageTaskLogsQuery* other);

  // implements Message ----------------------------------------------

  MessageTaskLogsQuery* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageTaskLogsQuery& from);
  void MergeFrom(const MessageTaskLogsQuery& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string taskID = 1;
  inline bool has_taskid() const;
  inline void clear_taskid();
  static const int kTaskIDFieldNumber = 1;
  inline const ::std::string& taskid() const;
  inline void set_taskid(const ::std::string& value);
  inline void set_taskid(const char* value);
  inline void set_taskid(const char* value, size_t size);
  inline ::std::string* mutable_taskid();
  inline ::std::string* release_taskid();
  inline void set_allocated_taskid(::std::string* taskid);

  // optional string token = 2;
  inline bool has_token() const;
  inline void clear_token();
  static const int kTokenFieldNumber = 2;
  inline const ::std::string& token() const;
  inline void set_token(const ::std::string& value);
  inline void set_token(const char* value);
  inline void set_token(const char* value, size_t size);
  inline ::std::string* mutable_token();
  inline ::std::string* release_token();
  inline void set_allocated_token(::std::string* token);

  // @@protoc_insertion_point(class_scope:MessageTaskLogsQuery)
 private:
  inline void set_has_taskid();
  inline void clear_has_taskid();
  inline void set_has_token();
  inline void clear_has_token();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* taskid_;
  ::std::string* token_;
  friend void  protobuf_AddDesc_MessageTaskLogsQuery_2eproto();
  friend void protobuf_AssignDesc_MessageTaskLogsQuery_2eproto();
  friend void protobuf_ShutdownFile_MessageTaskLogsQuery_2eproto();

  void InitAsDefaultInstance();
  static MessageTaskLogsQuery* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageTaskLogsQuery

// required string taskID = 1;
inline bool MessageTaskLogsQuery::has_taskid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageTaskLogsQuery::set_has_taskid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageTaskLogsQuery::clear_has_taskid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageTaskLogsQuery::clear_taskid() {
  if (taskid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    taskid_->clear();
  }
  clear_has_taskid();
}
inline const ::std::string& MessageTaskLogsQuery::taskid() const {
  // @@protoc_insertion_point(field_get:MessageTaskLogsQuery.taskID)
  return *taskid_;
}
inline void MessageTaskLogsQuery::set_taskid(const ::std::string& value) {
  set_has_taskid();
  if (taskid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    taskid_ = new ::std::string;
  }
  taskid_->assign(value);
  // @@protoc_insertion_point(field_set:MessageTaskLogsQuery.taskID)
}
inline void MessageTaskLogsQuery::set_taskid(const char* value) {
  set_has_taskid();
  if (taskid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    taskid_ = new ::std::string;
  }
  taskid_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageTaskLogsQuery.taskID)
}
inline void MessageTaskLogsQuery::set_taskid(const char* value, size_t size) {
  set_has_taskid();
  if (taskid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    taskid_ = new ::std::string;
  }
  taskid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageTaskLogsQuery.taskID)
}
inline ::std::string* MessageTaskLogsQuery::mutable_taskid() {
  set_has_taskid();
  if (taskid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    taskid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageTaskLogsQuery.taskID)
  return taskid_;
}
inline ::std::string* MessageTaskLogsQuery::release_taskid() {
  clear_has_taskid();
  if (taskid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = taskid_;
    taskid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageTaskLogsQuery::set_allocated_taskid(::std::string* taskid) {
  if (taskid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete taskid_;
  }
  if (taskid) {
    set_has_taskid();
    taskid_ = taskid;
  } else {
    clear_has_taskid();
    taskid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageTaskLogsQuery.taskID)
}

// optional string token = 2;
inline bool MessageTaskLogsQuery::has_token() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageTaskLogsQuery::set_has_token() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageTaskLogsQuery::clear_has_token() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageTaskLogsQuery::clear_token() {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_->clear();
  }
  clear_has_token();
}
inline const ::std::string& MessageTaskLogsQuery::token() const {
  // @@protoc_insertion_point(field_get:MessageTaskLogsQuery.token)
  return *token_;
}
inline void MessageTaskLogsQuery::set_token(const ::std::string& value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set:MessageTaskLogsQuery.token)
}
inline void MessageTaskLogsQuery::set_token(const char* value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageTaskLogsQuery.token)
}
inline void MessageTaskLogsQuery::set_token(const char* value, size_t size) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageTaskLogsQuery.token)
}
inline ::std::string* MessageTaskLogsQuery::mutable_token() {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageTaskLogsQuery.token)
  return token_;
}
inline ::std::string* MessageTaskLogsQuery::release_token() {
  clear_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = token_;
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageTaskLogsQuery::set_allocated_token(::std::string* token) {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete token_;
  }
  if (token) {
    set_has_token();
    token_ = token;
  } else {
    clear_has_token();
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageTaskLogsQuery.token)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageTaskLogsQuery_2eproto__INCLUDED
