// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageTaskAbort.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageTaskAbort.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MessageTaskAbort_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageTaskAbort_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageTaskAbort_2eproto() {
  protobuf_AddDesc_MessageTaskAbort_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageTaskAbort.proto");
  GOOGLE_CHECK(file != NULL);
  MessageTaskAbort_descriptor_ = file->message_type(0);
  static const int MessageTaskAbort_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageTaskAbort, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageTaskAbort, originalid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageTaskAbort, reason_),
  };
  MessageTaskAbort_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageTaskAbort_descriptor_,
      MessageTaskAbort::default_instance_,
      MessageTaskAbort_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageTaskAbort, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageTaskAbort, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageTaskAbort));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageTaskAbort_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageTaskAbort_descriptor_, &MessageTaskAbort::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageTaskAbort_2eproto() {
  delete MessageTaskAbort::default_instance_;
  delete MessageTaskAbort_reflection_;
}

void protobuf_AddDesc_MessageTaskAbort_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026MessageTaskAbort.proto\"B\n\020MessageTaskA"
    "bort\022\n\n\002id\030\001 \002(\t\022\022\n\noriginalID\030\002 \002(\t\022\016\n\006"
    "reason\030\003 \001(\t", 92);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageTaskAbort.proto", &protobuf_RegisterTypes);
  MessageTaskAbort::default_instance_ = new MessageTaskAbort();
  MessageTaskAbort::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageTaskAbort_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageTaskAbort_2eproto {
  StaticDescriptorInitializer_MessageTaskAbort_2eproto() {
    protobuf_AddDesc_MessageTaskAbort_2eproto();
  }
} static_descriptor_initializer_MessageTaskAbort_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MessageTaskAbort::kIdFieldNumber;
const int MessageTaskAbort::kOriginalIDFieldNumber;
const int MessageTaskAbort::kReasonFieldNumber;
#endif  // !_MSC_VER

MessageTaskAbort::MessageTaskAbort()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageTaskAbort)
}

void MessageTaskAbort::InitAsDefaultInstance() {
}

MessageTaskAbort::MessageTaskAbort(const MessageTaskAbort& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageTaskAbort)
}

void MessageTaskAbort::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  originalid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageTaskAbort::~MessageTaskAbort() {
  // @@protoc_insertion_point(destructor:MessageTaskAbort)
  SharedDtor();
}

void MessageTaskAbort::SharedDtor() {
  if (id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete id_;
  }
  if (originalid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete originalid_;
  }
  if (reason_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete reason_;
  }
  if (this != default_instance_) {
  }
}

void MessageTaskAbort::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageTaskAbort::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageTaskAbort_descriptor_;
}

const MessageTaskAbort& MessageTaskAbort::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageTaskAbort_2eproto();
  return *default_instance_;
}

MessageTaskAbort* MessageTaskAbort::default_instance_ = NULL;

MessageTaskAbort* MessageTaskAbort::New() const {
  return new MessageTaskAbort;
}

void MessageTaskAbort::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_id()) {
      if (id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        id_->clear();
      }
    }
    if (has_originalid()) {
      if (originalid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        originalid_->clear();
      }
    }
    if (has_reason()) {
      if (reason_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        reason_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessageTaskAbort::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MessageTaskAbort)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->id().data(), this->id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_originalID;
        break;
      }

      // required string originalID = 2;
      case 2: {
        if (tag == 18) {
         parse_originalID:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_originalid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->originalid().data(), this->originalid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "originalid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_reason;
        break;
      }

      // optional string reason = 3;
      case 3: {
        if (tag == 26) {
         parse_reason:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reason()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->reason().data(), this->reason().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "reason");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageTaskAbort)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageTaskAbort)
  return false;
#undef DO_
}

void MessageTaskAbort::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageTaskAbort)
  // required string id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->id(), output);
  }

  // required string originalID = 2;
  if (has_originalid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->originalid().data(), this->originalid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "originalid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->originalid(), output);
  }

  // optional string reason = 3;
  if (has_reason()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reason().data(), this->reason().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "reason");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->reason(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MessageTaskAbort)
}

::google::protobuf::uint8* MessageTaskAbort::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MessageTaskAbort)
  // required string id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->id(), target);
  }

  // required string originalID = 2;
  if (has_originalid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->originalid().data(), this->originalid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "originalid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->originalid(), target);
  }

  // optional string reason = 3;
  if (has_reason()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reason().data(), this->reason().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "reason");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->reason(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MessageTaskAbort)
  return target;
}

int MessageTaskAbort::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->id());
    }

    // required string originalID = 2;
    if (has_originalid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->originalid());
    }

    // optional string reason = 3;
    if (has_reason()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->reason());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageTaskAbort::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessageTaskAbort* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessageTaskAbort*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessageTaskAbort::MergeFrom(const MessageTaskAbort& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_originalid()) {
      set_originalid(from.originalid());
    }
    if (from.has_reason()) {
      set_reason(from.reason());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessageTaskAbort::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageTaskAbort::CopyFrom(const MessageTaskAbort& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageTaskAbort::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void MessageTaskAbort::Swap(MessageTaskAbort* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(originalid_, other->originalid_);
    std::swap(reason_, other->reason_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessageTaskAbort::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageTaskAbort_descriptor_;
  metadata.reflection = MessageTaskAbort_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
